Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
os.environ["PATH"] += ";C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext"

import saspy
#saspy.sascfg
sas = saspy.SASsession(cfgfile='C:\\Users\\rdominguez\\anaconda3\\Lib\\site-packages\\saspy\\sascfg_personal.py', java = 'C:\\Program Files\\SASHome\\SASPrivateJavaRuntimeEnvironment\\9.4\\jre\\bin\\java.exe')

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m      2[0m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124mPATH[39m[38;5;124m"[39m] [38;5;241m+[39m[38;5;241m=[39m [38;5;124m"[39m[38;5;124m;C:[39m[38;5;130;01m\\[39;00m[38;5;124mProgram Files[39m[38;5;130;01m\\[39;00m[38;5;124mSASHome[39m[38;5;130;01m\\[39;00m[38;5;124mSASFoundation[39m[38;5;130;01m\\[39;00m[38;5;124m9.4[39m[38;5;130;01m\\[39;00m[38;5;124mcore[39m[38;5;130;01m\\[39;00m[38;5;124msasext[39m[38;5;124m"[39m
[0;32m----> 4[0m [38;5;28;01mimport[39;00m [38;5;21;01msaspy[39;00m
[1;32m      5[0m [38;5;66;03m#saspy.sascfg[39;00m
[1;32m      6[0m sas [38;5;241m=[39m saspy[38;5;241m.[39mSASsession(cfgfile[38;5;241m=[39m[38;5;124m'[39m[38;5;124mC:[39m[38;5;130;01m\\[39;00m[38;5;124mUsers[39m[38;5;130;01m\\[39;00m[38;5;124mrdominguez[39m[38;5;130;01m\\[39;00m[38;5;124manaconda3[39m[38;5;130;01m\\[39;00m[38;5;124mLib[39m[38;5;130;01m\\[39;00m[38;5;124msite-packages[39m[38;5;130;01m\\[39;00m[38;5;124msaspy[39m[38;5;130;01m\\[39;00m[38;5;124msascfg_personal.py[39m[38;5;124m'[39m, java [38;5;241m=[39m [38;5;124m'[39m[38;5;124mC:[39m[38;5;130;01m\\[39;00m[38;5;124mProgram Files[39m[38;5;130;01m\\[39;00m[38;5;124mSASHome[39m[38;5;130;01m\\[39;00m[38;5;124mSASPrivateJavaRuntimeEnvironment[39m[38;5;130;01m\\[39;00m[38;5;124m9.4[39m[38;5;130;01m\\[39;00m[38;5;124mjre[39m[38;5;130;01m\\[39;00m[38;5;124mbin[39m[38;5;130;01m\\[39;00m[38;5;124mjava.exe[39m[38;5;124m'[39m)

[0;31mModuleNotFoundError[0m: No module named 'saspy'

